import Head from "next/head";
import Image from "next/image";
import Header from "../src/components/Header";
import Footer from "../src/components/Footer";

export default function Home() {
    return (
        <div data-theme="mytheme">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Header />
                <h1 className="text-red-500">Hello world</h1>
                <Footer />
            </main>
        </div>
    );
}
